### numpy ---> play with arrays

In [6]:
import numpy as np

In [7]:
simple_list = [6,7,8]
np.array(simple_list)

array([6, 7, 8])

In [8]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [9]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(5,20)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [11]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [12]:
np.arange(1,36,4)

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33])

In [13]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [14]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [19]:
np.ones((2,3),int)

array([[1, 1, 1],
       [1, 1, 1]])

In [21]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [25]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [26]:
np.linspace(0,4,10)

array([0.        , 0.44444444, 0.88888889, 1.33333333, 1.77777778,
       2.22222222, 2.66666667, 3.11111111, 3.55555556, 4.        ])

In [30]:
np.eye(10,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [33]:
np.random.rand(3,5)

array([[0.21976725, 0.94556755, 0.93515065, 0.17074417, 0.52416698],
       [0.05823741, 0.92040374, 0.1929956 , 0.48821243, 0.12477838],
       [0.36390344, 0.84644438, 0.59789036, 0.48244958, 0.40082475]])

In [37]:
arr=np.random.randn(2,4)
arr

array([[-0.04460168, -0.68003345, -1.473823  ,  1.02285334],
       [-0.82812343,  1.0726592 ,  1.04762676,  1.1790318 ]])

In [40]:
np.random.randint(1,100)

47

In [42]:
np.random.randint(20,50,100)

array([38, 30, 37, 28, 26, 23, 42, 41, 31, 31, 45, 44, 33, 48, 31, 29, 31,
       25, 49, 41, 44, 42, 20, 26, 37, 45, 25, 23, 27, 34, 40, 30, 42, 39,
       20, 23, 40, 20, 33, 25, 39, 41, 25, 24, 27, 36, 47, 39, 24, 39, 43,
       39, 34, 35, 25, 38, 27, 20, 41, 29, 21, 41, 33, 24, 40, 22, 23, 40,
       40, 36, 25, 48, 30, 27, 31, 41, 27, 44, 26, 39, 30, 38, 26, 33, 41,
       36, 48, 24, 35, 38, 41, 33, 22, 47, 39, 22, 43, 37, 41, 31])

In [44]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [46]:
rand_array=np.random.randint(0,10,50)
rand_array

array([6, 6, 4, 7, 6, 4, 0, 0, 6, 6, 5, 1, 1, 6, 9, 8, 5, 5, 3, 7, 5, 4,
       7, 4, 9, 8, 3, 0, 3, 0, 6, 1, 1, 4, 6, 1, 2, 1, 0, 8, 8, 5, 0, 0,
       9, 5, 1, 4, 9, 1])

In [48]:
sample_array.reshape(5,6)


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [49]:
sample_array.reshape(4,3)

ValueError: cannot reshape array of size 30 into shape (4,3)

In [50]:
rand_array.max()

9

In [51]:
rand_array.argmax()

14

In [52]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [53]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [56]:
a=np.random.rand(2,3)
a

array([[0.4999901 , 0.52471864, 0.53726877],
       [0.48560493, 0.14326078, 0.13709365]])

In [57]:
sample_array=np.arange(10,20)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [58]:
sample_array[0]

10

In [59]:
sample_array[2:5]

array([12, 13, 14])

In [61]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19])

In [65]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([ 10, 100, 100, 100,  14,  15,  16])

In [66]:
subset_sample_array[:]=1001
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])